SET NAMES UTF8;
DROP DATABASE IF EXISTS resumesql;
CREATE DATABASE resumesql CHARSET=UTF8;
USE resumesql;
CREATE TABLE message(
    id  INT PRIMARY KEY AUTO_INCREMENT,
    uname VARCHAR(32) NOT NULL,
    mail  VARCHAR(32) NOT NULL UNIQUE,
    content VARCHAR(128) NOT NULL);